---
title: "Diffractive array"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "baptiste Auguie"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4
    fig_caption: true
vignette: >
  %\VignetteIndexEntry{Diffractive array}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r demo, message=FALSE, echo=FALSE}
knitr::read_chunk("diffractive_array.R")
knitr::read_chunk("load.R")
```
```{r load, message=FALSE, echo=FALSE}
```
```{r setup, message=FALSE, echo=FALSE}
```
In this example we consider a 2D periodic arrangement of ellipsoids in a square array, with a separation of the order of the wavelength. The incident light is perpendicular to the array.

```{r cluster, rgl=TRUE,echo=-9,tidy=FALSE,fig.width=3,fig.height=3,fig.path="array-"}
```

## Influence of the array dimension

```{r comparison,echo=TRUE,tidy=FALSE,fig.path="array-"}
```

## Comparison with semi-analytical dipole summation

```{r analytical,echo=TRUE,tidy=FALSE,fig.path="array-"}
```