---
title: "Circular dichroism of a nanohelix"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "baptiste Auguie"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 4
    fig_caption: true
vignette: >
  %\VignetteIndexEntry{Circular dichroism of a nanohelix}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r demo, message=FALSE, echo=FALSE}
knitr::read_demo("helix_cd", package="cda")
knitr::read_chunk("load.R")
```
```{r load, message=FALSE, echo=FALSE}
```
```{r setup, message=FALSE, echo=FALSE}
```
A helix of more than 4 spheres is chiral, and displays optical activity. In contrast, even a small departure from sphericity allows clusters of only 2 ellipsoids to be (strongly) optically active. We compare both situations in this demo.

### Cluster definition
```{r cluster, rgl=TRUE,echo=-12,tidy=FALSE,fig.width=3,fig.height=3,fig.path="helix-"}
```


### Comparing spheres and ellipsoids

```{r comparison,echo=TRUE,tidy=FALSE,fig.path="helix-",fig.width=8}
```